version: '3.8'

services:
  api:
    container_name: excell-api
    #image: excell_api:v1
    build:
      context: ./../
      dockerfile: excell-api-local.dockerfile
      args:
        ENV: local
    ports:
      - 3001:8080
    volumes:
      - "./../src:/app/excell/code/src"
      - "./../docker/env/excell-api-local.env:/app/excell/code/.env"
    networks:
      excell:
        ipv4_address: 172.1.0.11
    links:
      - db
  db:
    hostname: db.excell.docker
    image: 'mysql:5.7.35'
    container_name: excell-db
    shm_size: 2gb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MAINT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
      - "./init-scripts:/docker-entrypoint-initdb.d"
    networks:
      excell:
        ipv4_address: 172.1.0.7

networks:
  excell:
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/16
          gateway: 172.1.0.1
